### ISSUE TITLE
Old Containous logo is used in light mode

### ISSUE THREAD

**Issue by matthieuh** [traefik/faency#106]

**Comment by paulocfjunior** [comment]
This doesn't happen with the new Traefik Labs logo.

Dark mode:
<img width="137" alt="Screen Shot 2020-11-18 at 10 53 36" src="https://user-images.githubusercontent.com/38889364/99538865-526d7f00-298c-11eb-91c3-707339f095f1.png">

Light mode:
<img width="174" alt="Screen Shot 2020-11-18 at 10 53 49" src="https://user-images.githubusercontent.com/38889364/99538887-58fbf680-298c-11eb-9f43-9c0f75d135dd.png">
