### ISSUE TITLE
[Button] Can't specify 'as' property directly on Button component

### ISSUE THREAD

**Issue by paulocfjunior** [traefik/faency#107]
We should be able to specify an `as` property on a component in a way that it's rendered using a different Primitive that it usually should use. For some reason, it's not possible to do this in some places.

**Comment by paulocfjunior** [comment]
After a discussion, we found out that it's a problem specific to a project, probably due to the Typescript version.
I think we could try to update the TS version and try to reproduce (and eventually solve it).

**Comment by seedy** [comment]
NB: `as` prop has been deprecated on Radix primitives in favour of `asChild` and `cloneElement` design pattern.

I think we should follow that, as they went away from polymorphism because of issues with typing and composition
