### ISSUE TITLE
[Checkbox] Update Checkbox style

### ISSUE THREAD

**Issue by paulocfjunior** [traefik/faency#149]
### Dark theme
![Screen Shot 2021-10-01 at 11 44 31](https://user-images.githubusercontent.com/38889364/135639672-52cf2ad8-1e2c-43f3-8641-e265d5b85a2d.png)

### Light theme
![Screen Shot 2021-10-01 at 11 44 40](https://user-images.githubusercontent.com/38889364/135639685-922cb4c9-26b3-4bb4-be22-c04e19157c33.png)

**Comment by seedy** [comment]
@matthieuh is this issue still ongoing? Is there work left?
