### ISSUE TITLE
Update Card style

### ISSUE THREAD

**Issue by matthieuh** [traefik/faency#166]
![Screen Shot 2021-10-26 at 13 55 41](https://user-images.githubusercontent.com/1550192/138872666-2ae44c02-57ad-45f6-8ef1-28dd24cfeac5.png)
![Screen Shot 2021-10-26 at 13 55 32](https://user-images.githubusercontent.com/1550192/138872669-bd7157c0-eb39-466c-9fcf-6ecc68aef8e4.png)

**Comment by seedy** [comment]
Closing as already done
