### ISSUE TITLE
[Tooltip] Update tooltip styles

### ISSUE THREAD

**Issue by seedy** [traefik/faency#196]
### Description

There is no design system page for the Tooltip UI component. 

This issue is here as a reminder task until we'll get a mockup.

### Radix-ui issue tracking

There's an ongoing a11y issue on the radix-ui primitive : https://github.com/radix-ui/primitives/issues/620

### a11y concerns: interactive tooltip content

After some reading, I'd put a warning on interactive content inside tooltips : some authorities recommend that tooltips should not have any interactive elements inside their content :
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role
- https://github.com/radix-ui/primitives/issues/620#issuecomment-933896028
- https://sarahmhigley.com/writing/tooltips-in-wcag-21/#best-practices-summary

Quoting [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role): 

> Because the tooltip itself never receives focus and is not in the tabbing order, a tooltip can not contain interactive elements like links, inputs, or buttons.

**Comment by gndz07** [comment]
No longer relevant.
