### ISSUE TITLE
[Icons] exports

### ISSUE THREAD

**Issue by seedy** [traefik/faency#236]
#### `@radix-ui/react-icons`

Export the icons?

For now we use some of those icons inside components, but don't export icons.

- `Menu` => `CheckIcon`
- `Checkbox` => `CheckIcon`
- `Dialog` => `Cross1Icon`
- `DropdownMenu` => `CheckIcon`
- `Select` => `CaretSortIcon`
- `TextField` => `ExclamationTriangleIcon`, `CrossCircledIcon`, `EyeOpenIcon`, `EyeClosedIcon`

For reusability from a dependent project, would it be useful to re-export all radix icons? 

#### AccessibleIcon utility wrapper

https://www.radix-ui.com/docs/primitives/utilities/accessible-icon

This util could be useful for other projects to wrap other icons with this layer of a11y

**Comment by gndz07** [comment]
No longer relevant.
