### ISSUE TITLE
[Link] update primary variant styles

### ISSUE THREAD

**Issue by seedy** [traefik/faency#318]
# Description

Variant primary does not match mockup in light mode:

- mockup
![image](https://user-images.githubusercontent.com/3367393/158361957-085bc670-0116-467d-a67c-28321198f991.png)

- result
![image](https://user-images.githubusercontent.com/3367393/158362086-c1a6abd6-0a9d-49f5-b079-6bd903f1f17a.png)

**Comment by gndz07** [comment]
No longer relevant
