### ISSUE TITLE
[Study] Rollup: replace plugin typescript by plugin swc

### ISSUE THREAD

**Issue by seedy** [traefik/faency#338]
# Description

https://github.com/mentaljam/rollup-plugin-swc

https://reactjsexample.com/use-swc-with-rollup-to-transform-esnext-and-typescript-code/

> [SWC](https://swc.rs/) is an extensible Rust-based platform for the next generation of fast developer tools. This plugin is designed to replace rollup-plugin-typescript2, @rollup/plugin-typescript, @rollup/plugin-babel and rollup-plugin-terser for you.

**Comment by paulocfjunior** [comment]
## Findings

Currently, when using `swc` for typescript projects, we are still required to run `tsc` to generate the `.d.ts` files. This is the most time-consuming part of the build (taking around _40 sec_ to finish). The `swc` compiler takes only half a second to finish. 
> ℹ️  _Our current build structure takes **100 seconds** to generate the `dist` folder._

`swc` is planning to generate the `.d.ts` files by itself as it's mentioned in [this article](https://kdy1.dev/posts/2022/1/tsc-go) (and this [issue](https://github.com/swc-project/swc/issues/571)) which will allow users to get rid of `tsc`. It will also be able to bundle the files, so it may replace `rollup` itself.

On the other hand, the Typescript team seems to be [aware](https://github.com/microsoft/TypeScript/issues/38573#issuecomment-628774832) that there's room to improve the `tsc` building/type-checking speed, they just don't seem to prioritize that right now, but there's a possibility that they do something about it in the future. 

## Test results

I was able to build the lib using `swc` + `tsc`.

![Screen Shot 2022-04-08 at 01 03 21](https://user-images.githubusercontent.com/38889364/162360269-538d6ceb-d2e8-47b6-b6fd-bfe4983abfa0.png)
> The whole process took 45s.

## Conclusion

From here, we have 2 options:
- [Faster] Use a mixed approach of `swc` + `tsc` to have the build working 2,5x faster, having in mind that `swc` is **under heavy development**.
- [Safer] Keep the current build structure (maybe just upgrade the libs used) and wait for `swc` to be ready to generate `.d.ts` files

**Comment by seedy** [comment]
Closing with conclusions validated
